[dependencies]
solana-sdk = "1.18" # Or your specific version
quinn = "0.10"      # QUIC implementation
tokio = { version = "1", features = ["full"] }
bincode = "1.3"
anyhow = "1.0"
rustls = "0.21"     # For TLS configuration
rcgen = "0.12"      # For generating self-signed certs in examples
std_socket = { package = "socket2", version = "0.5" } # For quinn example if needed